Software backends draft (easybuild, conda, apptainer)
omnibenchmark/omnibenchmark pull request #9
Opened 2024-08-19 09:12 UTC by imallona

## Ticket

https://github.com/omnibenchmark/omni_workflow/issues/9

## Description

Draft software management backends: easybuild (coupled to singularity; or coupled to lmod) and conda backends.

CLI:

- `ob software envmodules build`  to manage envmodules-based software installations. Uses easybuild to build software.                                                                                                            
- `ob software singularity build` and `ob software singularity push` to manage singularity- (apptainer-) based software installations. Uses easybuild to build software.
- `ob software conda pin` to make conda yamls reproducible via snakedeploy pinning. Depends on mamba.

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My CLI method respects the signature defined in the task.
- [ ] I have documented the CLI method accordingly.
- [x] I have added tests to cover my changes.
- [x] I have added a CHANGELOG entry.

## Remarks for the reviewer:

Major changes regarding install. Mamba is a dependency, so conda is offerend as a backend for software installs, mainly [snakedeploy-style conda environments pinning](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#freezing-environments-to-exactly-pinned-packages). Hence, omnibenchmark is not pip (only) installable anymore, and needs to be installed in a conda env. A recipe is provided at `test-environment.yml`. Tests run on this with `micromamba`.

Similarly, python >= 3.12 is needed to provide snakemake >=8.

Further tuning of `pyproject.toml` is needed, so the core/extras/dependencies are sane.

2024-08-23 07:57 UTC, imallona commented
FYI I'm currently adding docker capabilities - for Mac users, mainly

2024-08-27 10:56 UTC, DanInci requested changes

2024-08-27 10:56 UTC, DanInci commented on omni/cli/soft.py
> +):
For running the benchmark CLI command, the argument is called `--cores`.
Should we unify the interface then? Go with `--cores` or `--threads`? Also knowing that for running the benchmark, cores has a completely different meaning for Snakemake.

2024-08-27 10:56 UTC, DanInci commented on omni/cli/soft.py
> +        sys.exit()
Instead of using `print` we should use `typer.echo("", err=True, color=typer.colors.RED)`

2024-08-27 10:56 UTC, DanInci commented on omni/cli/soft.py
> +
Replace print with `typer.echo`

2024-08-27 10:56 UTC, DanInci commented on omni/cli/soft.py
> +    print("DONE\n.")
Replace print with `typer.echo`

2024-08-27 10:56 UTC, DanInci commented on omni/cli/soft.py
> +    print("DONE")
Replace print with `typer.echo`

2024-08-27 10:56 UTC, DanInci commented on omni/cli/soft.py
> +        print("Failed:", ret)
Replace print with `typer.echo`

2024-08-27 10:56 UTC, DanInci commented on omni/software/common.py
> +        return print("ERROR:", e)
This is a weird looking function, why return None? 
I'd change the print with `typer.echo` and change the function signature to reflect that catching an exception with return None.

2024-08-27 10:56 UTC, DanInci commented on omni/software/conda_backend.py
> +    )
I wonder if this conda pinning functionality should go through the `WorkflowEngine` api, since its an implementation detail specific to snakemake for now, right?

2024-08-27 10:56 UTC, DanInci commented on omni/software/easybuild_backend.py
> +
I assume this is not Windows compatible, right?

2024-08-27 11:17 UTC, DanInci commented on omni/cli/soft.py
> +):
go with cores, I'll change

2024-08-27 11:21 UTC, DanInci commented on omni/cli/soft.py
> +        sys.exit()
```
cli = typer.Typer(
    add_completion=True,
    no_args_is_help=True,
    pretty_exceptions_short=True,
    rich_markup_mode=None,
    pretty_exceptions_enable=False,
    help="Manage benchmark-specific software installations.",
)
```

Disable pretty exceptions in other CLI.

2024-08-27 13:46 UTC, imallona commented on omni/software/easybuild_backend.py
> +
I think it's not. Perhaps WSL compatible? but I doubt it

2024-08-27 15:00 UTC, DanInci commented on omni/software/easybuild_backend.py
> +
We can scope this out for the software feature for now. 
I guess if you have all the necessary dependencies on windows, you can anyways run using `host` backend

2024-08-27 15:06 UTC, DanInci approved these changes
LGTM ! Let's merge this feature .

2024-08-27 15:22 UTC, imallona commented on omni/software/common.py
> +        return print("ERROR:", e)
fixed, thanks

2024-08-27 15:49 UTC, merged